# Generated by Django 4.2.5 on 2023-09-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('archive', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='timetable_class_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('a', 'Available'), ('c', 'Cancelled'), ('h', 'On Hold')], default='a', help_text='Class status', max_length=1)),
                ('gym_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ERP.gym_class')),
            ],
            options={
                'ordering': ['time_slot'],
            },
        ),
    ]
