# Generated by Django 4.2.5 on 2023-09-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable_class_instance',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
