# Generated by Django 4.2.5 on 2023-09-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_timetable_class_instance_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable_class_instance',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetable_class_instance',
            name='time_slot',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
