# Generated by Django 4.2.5 on 2023-10-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0004_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="mon6",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mon6",
                to="ERP.timetable_class_instance",
            ),
        ),
    ]
