# Generated by Django 4.2.5 on 2023-10-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0006_timetable_mon10_timetable_mon11_timetable_mon12_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable_class_instance",
            name="gym_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="ERP.gym_class",
            ),
        ),
    ]
