# Generated by Django 4.2.5 on 2023-10-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0008_timetable_tue10_timetable_tue11_timetable_tue12_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetable_class_instance", options={"ordering": ["time_slot", "day"]},
        ),
    ]
