# Generated by Django 4.2.5 on 2023-10-16 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_timetable_fri10_timetable_fri11_timetable_fri12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='mon10',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon10', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon11',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon11', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon12',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon12', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon13',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon13', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon14',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon14', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon15',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon15', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon16',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon16', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon17',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon17', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon18',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon18', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon5', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon6',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon6', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon7',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon7', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon8',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon8', to='ERP.timetable_class_instance'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon9',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon9', to='ERP.timetable_class_instance'),
        ),
    ]
