# Generated by Django 4.2.5 on 2023-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0012_alter_timetable_mon10_alter_timetable_mon11_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable_class_instance",
            name="current_participants",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="timetable_class_instance",
            name="max_participants",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
