# Generated by Django 4.2.5 on 2023-10-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0013_timetable_class_instance_current_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable_class_instance",
            name="xd",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
