# Generated by Django 4.2.5 on 2023-10-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ERP", "0014_timetable_class_instance_xd"),
    ]

    operations = [
        migrations.RemoveField(model_name="timetable_class_instance", name="xd",),
    ]
