# Generated by Django 4.2.5 on 2023-10-20 05:08

import ERP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0018_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=ERP.models.user_profile_image_path),
        ),
    ]
