# Generated by Django 4.2.5 on 2023-10-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0020_alter_userprofile_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'permissions': [('update_timetable', 'Can update the Timetable')]},
        ),
    ]
