# Generated by Django 4.2.5 on 2023-10-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0021_alter_timetable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
