# Generated by Django 4.2.5 on 2023-10-23 03:43

import ERP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0023_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=ERP.models.user_profile_image_path),
        ),
    ]
