# Generated by Django 4.2.5 on 2024-10-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0024_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym_class',
            name='max_participants',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
