# Generated by Django 4.2.5 on 2024-10-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0025_gym_class_max_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable_class_instance',
            name='max_participants',
        ),
    ]
