# Generated by Django 4.2.5 on 2024-10-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0026_remove_timetable_class_instance_max_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable_class_instance',
            options={},
        ),
    ]
