# Generated by Django 4.2.5 on 2024-10-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0027_alter_timetable_class_instance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable_class_instance',
            options={'ordering': ['time_slot', 'day']},
        ),
    ]
