# Generated by Django 4.2.5 on 2025-04-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0030_userprofile_email_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_payment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_payment',
            field=models.DateTimeField(null=True),
        ),
    ]
