# Generated by Django 4.2.5 on 2025-06-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0031_userprofile_is_paid_userprofile_last_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
    ]
