# Generated by Django 4.2.5 on 2023-09-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('archive', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now=True, verbose_name='time published')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('active_member', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='static/profile_pictures')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'join_date'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('mon10', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon10', to='catalog.gym_class')),
                ('mon11', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon11', to='catalog.gym_class')),
                ('mon12', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon12', to='catalog.gym_class')),
                ('mon13', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon13', to='catalog.gym_class')),
                ('mon14', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon14', to='catalog.gym_class')),
                ('mon15', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon15', to='catalog.gym_class')),
                ('mon16', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon16', to='catalog.gym_class')),
                ('mon17', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon17', to='catalog.gym_class')),
                ('mon6', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon6', to='catalog.gym_class')),
                ('mon7', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon7', to='catalog.gym_class')),
                ('mon8', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon8', to='catalog.gym_class')),
                ('mon9', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon9', to='catalog.gym_class')),
                ('tue6', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue6', to='catalog.gym_class')),
                ('tue7', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue7', to='catalog.gym_class')),
                ('tue8', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue8', to='catalog.gym_class')),
                ('tue9', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue9', to='catalog.gym_class')),
            ],
        ),
    ]
