# Generated by Django 4.2.5 on 2023-09-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='thur10',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur10', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur11',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur11', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur12',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur12', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur13',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur13', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur14',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur14', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur15',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur15', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur16',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur16', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur17',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur17', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur6',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur6', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur7',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur7', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur8',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur8', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur9',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur9', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue10',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue10', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue11',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue11', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue12',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue12', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue13',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue13', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue14',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue14', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue15',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue15', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue16',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue16', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue17',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue17', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed10',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed10', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed11',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed11', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed12',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed12', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed13',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed13', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed14',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed14', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed15',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed15', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed16',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed16', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed17',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed17', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed6',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed6', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed7',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed7', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed8',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed8', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed9',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed9', to='catalog.gym_class'),
        ),
    ]
