# Generated by Django 4.2.5 on 2023-09-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_timetable_thur10_timetable_thur11_timetable_thur12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fri10',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri10', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri11',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri11', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri12',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri12', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri13',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri13', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri14',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri14', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri15',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri15', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri16',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri16', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri17',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri17', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri6',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri6', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri7',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri7', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri8',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri8', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri9',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri9', to='catalog.gym_class'),
        ),
    ]
