# Generated by Django 4.2.5 on 2023-09-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_timetable_fri10_timetable_fri11_timetable_fri12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='sat10',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat10', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat11',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat11', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat12',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat12', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat13',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat13', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat14',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat14', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat15',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat15', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat16',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat16', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat17',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat17', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat6',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat6', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat7',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat7', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat8',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat8', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat9',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat9', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun10',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun10', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun11',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun11', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun12',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun12', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun13',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun13', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun14',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun14', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun15',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun15', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun16',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun16', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun17',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun17', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun6',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun6', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun7',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun7', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun8',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun8', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun9',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun9', to='catalog.gym_class'),
        ),
    ]
