# Generated by Django 4.2.5 on 2023-09-22 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_timetable_sat10_timetable_sat11_timetable_sat12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fri18',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri18', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fri5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fri5', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='mon18',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon18', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='mon5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon5', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat18',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat18', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sat5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sat5', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun18',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun18', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sun5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sun5', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur18',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur18', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thur5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thur5', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue18',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue18', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='tue5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tue5', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed18',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed18', to='catalog.gym_class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='wed5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wed5', to='catalog.gym_class'),
        ),
    ]
